local p = require("robot_dreams.palette")
return {
	markdownH1 = { fg = p.title, bold = true },
	markdownH2 = { fg = p.fg, bold = true },
	markdownH3 = { fg = p.accent, bold = true },
	markdownH4 = { fg = p.keyword, bold = true },
	markdownH5 = { fg = p.type, bold = true },
	markdownH6 = { fg = p.variant, bold = true },
	markdownHeadingDelimiter = { fg = p.comment_doc },
	markdownHeadingRule = { fg = p.comment_doc },
	markdownId = { fg = p.keyword },
	markdownIdDeclaration = { fg = p.title },
	markdownIdDelimiter = { fg = p.keyword },
	markdownLinkDelimiter = { fg = p.comment_doc },
	markdownLinkText = { fg = p.blue, italic = true },
	markdownListMarker = { fg = p.accent },
	markdownOrderedListMarker = { fg = p.accent },
	markdownRule = { fg = p.comment_doc },
	markdownUrl = { fg = p.cyan, bg = p.none },
	markdownBlockquote = { fg = p.comment },
	markdownBold = { fg = p.fg, bg = p.none, bold = true },
	markdownItalic = { fg = p.fg, bg = p.none, italic = true },
	markdownCode = { fg = p.orange },
	markdownCodeBlock = { fg = p.orange },
	markdownCodeDelimiter = { fg = p.comment_doc },
}
