local p = require("robot_dreams.palette")

return {
	NavicIconsFile = { fg = p.fg, bg = p.none },
	NavicIconsModule = { fg = p.yellow, bg = p.none },
	NavicIconsNamespace = { fg = p.fg, bg = p.none },
	NavicIconsPackage = { fg = p.fg, bg = p.none },
	NavicIconsClass = { fg = p.type, bg = p.none },
	NavicIconsMethod = { fg = p.function_, bg = p.none },
	NavicIconsProperty = { fg = p.variable, bg = p.none },
	NavicIconsField = { fg = p.variable, bg = p.none },
	NavicIconsConstructor = { fg = p.constructor, bg = p.none },
	NavicIconsEnum = { fg = p.enum, bg = p.none },
	NavicIconsInterface = { fg = p.type, bg = p.none },
	NavicIconsFunction = { fg = p.function_, bg = p.none },
	NavicIconsVariable = { fg = p.variable, bg = p.none },
	NavicIconsConstant = { fg = p.constant, bg = p.none },
	NavicIconsString = { fg = p.string, bg = p.none },
	NavicIconsNumber = { fg = p.number, bg = p.none },
	NavicIconsBoolean = { fg = p.constant, bg = p.none },
	NavicIconsArray = { fg = p.fg_muted, bg = p.none },
	NavicIconsObject = { fg = p.fg_muted, bg = p.none },
	NavicIconsKey = { fg = p.keyword, bg = p.none },
	NavicIconsKeyword = { fg = p.keyword, bg = p.none },
	NavicIconsNull = { fg = p.red, bg = p.none },
	NavicIconsEnumMember = { fg = p.constant, bg = p.none },
	NavicIconsStruct = { fg = p.type, bg = p.none },
	NavicIconsEvent = { fg = p.keyword, bg = p.none },
	NavicIconsOperator = { fg = p.operator, bg = p.none },
	NavicIconsTypeParameter = { fg = p.type, bg = p.none },
	NavicText = { fg = p.fg, bg = p.none },
	NavicSeparator = { fg = p.fg_muted, bg = p.none },
}
