local p = require("robot_dreams.palette")
local config = require("robot_dreams.config")
local styles = vim.tbl_map(function(value)
	return setmetatable(value, {
		__add = function(a, b)
			return vim.tbl_extend("force", a, b)
		end,
	})
end, config.styles)
return {
	["@boolean"] = { fg = p.constant } + styles.booleans,
	["@constructor"] = { fg = p.constructor },
	["@constant.builtin"] = { fg = p.constant },
	["@keyword.function"] = { fg = p.keyword } + styles.functions,
	["@namespace"] = { fg = p.fg, italic = true },
	["@parameter"] = { fg = p.variable },
	["@property"] = { fg = p.variable },
	["@punctuation"] = { fg = p.fg },
	["@punctuation.delimiter"] = { fg = p.delimiter },
	["@punctuation.bracket"] = { fg = p.bracket },
	["@punctuation.special"] = { fg = p.orange },
	["@string.documentation"] = { fg = p.comment_doc } + styles.comments,
	["@string.regex"] = { fg = p.orange },
	["@string.escape"] = { fg = p.yellow },
	["@string.special.url"] = { fg = p.cyan, underline = true },
	["@symbol"] = { fg = p.enum },
	["@tag"] = { fg = p.keyword },
	["@tag.attribute"] = { fg = p.variable, italic = true },
	["@tag.delimiter"] = { fg = p.fg },
	["@type.builtin"] = { fg = p.type },
	["@variable"] = { fg = p.variable } + styles.variables,
	["@variable.builtin"] = { fg = p.cyan } + styles.variables,
	["@variable.parameter"] = { fg = p.variable } + styles.variables,
	["@constructor.javascript"] = { fg = p.constructor },
	["@keyword.clojure"] = { fg = p.keyword } + styles.keywords,
	["@keyword.import"] = { fg = p.keyword } + styles.keywords,
	["@text.underline"] = { link = "Underlined" },
	["@text.strong"] = { bold = true },
	["@text.strikethrough"] = { strikethrough = true },
	["@text.italic"] = { italic = true },
	["@markup.heading"] = { fg = p.title, bold = true },
	["@markup.heading.1"] = { fg = p.title, bold = true },
	["@markup.heading.1.marker"] = { link = "@comment" },
	["@markup.heading.2"] = { fg = p.title, bold = true },
	["@markup.heading.2.marker"] = { link = "@comment" },
	["@markup.heading.3"] = { fg = p.title, bold = true },
	["@markup.heading.3.marker"] = { link = "@comment" },
	["@markup.heading.4"] = { fg = p.title, bold = true },
	["@markup.heading.4.marker"] = { link = "@comment" },
	["@markup.heading.5"] = { fg = p.title, bold = true },
	["@markup.heading.5.marker"] = { link = "@comment" },
	["@markup.heading.6"] = { fg = p.title, bold = true },
	["@markup.heading.6.marker"] = { link = "@comment" },
	["@markup.link"] = { fg = p.blue },
	["@markup.link.label"] = { fg = p.blue },
	["@markup.link.url"] = { fg = p.cyan },
	["@markup.list"] = { fg = p.accent, bold = true },
	["@markup.list.checked"] = { fg = p.green },
	["@markup.list.unchecked"] = { fg = p.fg_muted },
	["@markup.raw.block"] = { fg = p.orange },
	["@markup.raw.delimiter"] = { fg = p.fg },
	["@markup.quote"] = { fg = p.comment },
	["@markup.list.checked.markdown"] = { fg = p.string },
	["@markup.underline"] = { link = "@text.underline" },
	["@markup.strong"] = { link = "@text.strong" },
	["@markup.italic"] = { link = "@text.italic" },
	["@markup.strikethrough"] = { link = "@text.strikethrough" },
}
