local p = require("gentleman_kanagawa_blur.palette")
return {
	markdownH1 = { fg = p.title, bold = true },
	markdownH2 = { fg = p.primary, bold = true },
	markdownH3 = { fg = p.enum, bold = true },
	markdownH4 = { fg = p.tag, bold = true },
	markdownH5 = { fg = p.type, bold = true },
	markdownH6 = { fg = p.variant, bold = true },
	markdownHeadingDelimiter = { fg = p.comment_doc },
	markdownHeadingRule = { fg = p.comment_doc },
	markdownId = { fg = p.tag },
	markdownIdDeclaration = { fg = p.title },
	markdownIdDelimiter = { fg = p.tag },
	markdownLinkDelimiter = { fg = p.comment_doc },
	markdownLinkText = { fg = p.link_text, italic = true },
	markdownListMarker = { fg = p.enum },
	markdownOrderedListMarker = { fg = p.enum },
	markdownRule = { fg = p.comment_doc },
	markdownUrl = { fg = p.link_uri, bg = p.none },
	markdownBlockquote = { fg = p.comment },
	markdownBold = { fg = p.primary, bg = p.none, bold = true },
	markdownItalic = { fg = p.primary, bg = p.none, italic = true },
	markdownCode = { fg = p.string },
	markdownCodeBlock = { fg = p.string },
	markdownCodeDelimiter = { fg = p.comment_doc },
}
