# Fondo basado en captura de pantalla + blur
background {
  # activar captura de pantalla del escritorio
  path = screenshot
  
  # blur tipo i3lock-fancy
  blur_passes = 2
  blur_size = 6
}

# Reloj en el centro
label {
  text = $TIME
  font_size = 42
  color = rgba(255,255,255,0.9)
  position = 0, 120
}

label {
  text = cmd[update:1000] echo "$(date +"%A, %d de %B del %Y")" | sed 's/^\(.\)/\U\1/'
  font_size = 18
  color = rgba(255,255,255,0.7)
  position = 0, 170
}
